from . import student
from . import course
from . import batch
from . import category
from . import admission
from . import admission_register
from . import student_course
from . import tutor
from . import employees
from . import teachers
from . import classrooms
from . import skills_teachers
from . import attendances_teachers
from . import attendances_students
from . import attendances_students_line
from . import attendances_students_sheet
from . import res_config_settings